### ISSUE TITLE
Android app not getting built after upgrading to 1.8.20

### ISSUE THREAD

**Issue by ursnj** [numandev1/react-native-compressor#244]
### Current behavior

Throwing this error @ 1.8.20 but same working in 1.8.18

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-compressor:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

### Platform

- [X] Android
- [X] iOS

**Comment by numandev1** [comment]
@ursnj are you using turbo module or not?

**Comment by ursnj** [comment]
No @numandev1 not using turbo modules. its just same code working in 1.8.19 but not working with 1.8.20 :(

**Comment by numandev1** [comment]
@ursnj fixed released into `1.8.21`

**Comment by ursnj** [comment]
Thanks @numandev1
